INSERT INTO PRODUCT (PRICE, CATEGORY, NAME) VALUES (100.0, 'CATEGORIA 1', 'PRODUTO 1');
INSERT INTO PRODUCT (PRICE, CATEGORY, NAME) VALUES (100.0, 'CATEGORIA 2', 'PRODUTO 2');
INSERT INTO PRODUCT (PRICE, CATEGORY, NAME) VALUES (100.0, 'CATEGORIA 3', 'PRODUTO 3');